### ISSUE TITLE
Show when last inspection was completed

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#125]
We are discussing the business rules of how often should an inspection be completed or when should an inspection NOT be completed.  We feel it would be helpful if we knew when the last inspection was completed and possibly which inspection.  Maybe it could be inside the inspection tab.
Not sure if this would be handled by DI or D3-API.

**Comment by DanielCaspers** [comment]
Ideas from brainstorming call

1.  Consider creating a notation structure where checklist items are measured against "inspection intervals", much like a car's owners manual recommended maintenance schedule.
2. Checklists could be dynamic according to business rules. For example, we could device checklists that consisted only items that we feel are relevant to inspect based on rules per checklist item. This could phase out the need for most checklists.
3. Checklist items could have visibility or applicability by the role of the user completing a dynamic list, instead of by them choosing the list that best fits their role.
4. Direct marketing could be performed based off of a lack of inspection interval data, such as if brakes or tires haven't been inspected in a timely fashion. 
5. The DI database can hold the checklists which have been merged into an inspection as metadata of each inspection, if needed.

**Comment by DanielCaspers** [comment]
This functionality exists through a level of indirection.

In Vehicle History tab, for each entry, one can see if an inspection was performed. If one was performed, a link to the report can be opened. It requires more detective work, but the info is all there
