### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/DigitalInspection#27]
Each checklist item must have 0 or more measurements.

A measurement consists of

- **Label**  describing what the measurement pertains to. Important if an item has multiple measurements. _Ex. Left Front tire could have Air Pressure and Tread Depth_
- **Minimum value**, integer
- **Maximum value**, integer
- **Step size**, integer (based on decision in comments)
- **Unit of measure** Admin-definable text for describing a measure's meaning. As min and max values must be integers >= 0, this must contain any knowledge of fractions.  
_Ex: Tire Pressure could be from 0 PSI to 120 PSI, with step size of 1, or Tread Depth could be 0 to 32 (32nds inch) with a step size of 1_

**Comment by scaspers** [comment]
First choice would be that Unit of Measure should be an admin definable text.  Second would be to make it hard coded.

**Comment by DanielCaspers** [comment]
There is no expectation of conversion, right? No math, just user definable text?

**Comment by scaspers** [comment]
Yes, just text.  Do you need to define length?

**Comment by DanielCaspers** [comment]
Nope :)

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy , which would you prefer? No real implementation time difference either way. 

1. Step size is always an integer, and when fractions are desired, fraction must be put into the label, or
2. Step size can be integer or decimal, so the units don't have fractions in them. Step size will NOT support pure fractions (ie. numerator/denominator) or rounding (think 3rds expressed as 0.333, etc)

**Comment by YoMurphy** [comment]
I'd say decimal will work in every scenario I can think of.  Tires are the only area that fraction is common but it would still be understood as a decimal entry with a fraction description. ie. 3.5 /32nds.


-------- Original message --------From: Daniel Caspers <notifications@github.com> Date: 4/2/17  11:54 PM  (GMT-06:00) To: DanielCaspers/DigitalInspection <DigitalInspection@noreply.github.com> Cc: YoMurphy <rick.murphy@murphyauto.com>, Mention <mention@noreply.github.com> Subject: Re: [DanielCaspers/DigitalInspection] Measurements (#27) 
@scaspers @YoMurphy , which would you prefer? No real implementation time difference either way.

Step size is always an integer, and when fractions are desired, fraction must be put into the label, or
Step size can be integer or decimal, so the units don't have fractions in them. Step size will NOT support pure fractions (ie. numerator/denominator) or rounding (think 3rds expressed as 0.333, etc)


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielCaspers/DigitalInspection","title":"DanielCaspers/DigitalInspection","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielCaspers/DigitalInspection"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielCaspers in #27: @scaspers @YoMurphy , which would you prefer? No real implementation time difference either way. \r\n\r\n1. Step size is always an integer, and when fractions are desired, fraction must be put into the label, or\r\n2. Step size can be integer or decimal, so the units don't have fractions in them. Step size will NOT support pure fractions (ie. numerator/denominator) or rounding (think 3rds expressed as 0.333, etc)\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/DanielCaspers/DigitalInspection/issues/27#issuecomment-291048552"}}}

**Comment by scaspers** [comment]
I would say option 1, integer only

Steve Caspers
President
Murphy Automotive, Inc.
ProTech Automotive  |  Grandview Tire & Auto  |  Edina Tire & Auto
Office: 952-997-3310
Mobile: 651-260-0664

**Comment by DanielCaspers** [comment]
Bad me. Here are the commits which provided the Measurements Feature.

cddbc00a89243b92ac0738d4b1381c5743e7d97e
f330d3b077c4a385de070db367517bef8c025436
17c87223ba53cdbfdf0ec3cedc752aa7b6acddd3
0689717666bb49a0b554a41b3821da80239d295a

If there is something user facing I missed, we can re-open this ticket once you guys get the chance to play with it. From what I can tell though, the configuration of this is all good to go.
