### ISSUE TITLE
Make "Work Orders" heading a link to the WorkOrders page

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#56]
![capture](https://user-images.githubusercontent.com/12421599/28828367-2ab9db54-7696-11e7-8a0e-722343548a33.JPG)

**Comment by DanielCaspers** [comment]
You'll be happy to know I snuck in this UX improvement. Its checked in, but won't deploy until we do DB fixes. 

However, I've made the fix far more generalized than in the description. My thinking was that this text is ALWAYS a link, no matter the feature

I can have fine grain control down to any page with a unique URL ("Checklists/Index", "WorkOrders/Index") etc, but have configured it so that certain feature groups behave the same.  Here's how its configured.

Home -> Link to current page (for now)
About -> Link to current page (for now)
**Work Orders features -> Link to work orders table**
**Inspection table -> Link to work orders table** . @scaspers @YoMurphy ,
 I did this for quick navigation out so hopefully switching work orders is easier. Perhaps I should rename "Inspections" when in an Inspection to "Work Orders" to make that link behavior clearer? Reopen if you think I should change. Its only a few lines.

LMK if thoughts on how to configure differently (when it comes to the feature names in the top left, or where those links point to).
