### ISSUE TITLE
Canned response creation

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#60]
When making new canned responses in a checklist item the new response should be inserted at the top if possible so that user does not have to scroll to bottom to fill out and then scroll to the top to save.
OR
Have the toolbar with save button static and the screen auto scroll to new canned response.

**Comment by DanielCaspers** [comment]
What if I made Add Measurement and Add Canned Response into dialogs? 

Then the page only has delete, and the save state is more sane for the form too, since the user can't get in a state where work is lost.

**Comment by scaspers** [comment]
Sounds good.  Can the list also be sorted (Alpha)?

**Comment by DanielCaspers** [comment]
Yes, that's very easy. Would you like measurements sorted as well?

**Comment by scaspers** [comment]
Probably not needed as there will not be a long list of measurements like there will be with canned responses.  You maybe could list measurements before the responses though?

**Comment by DanielCaspers** [comment]
@scaspers, the  

1. Measurements are now before canned responses
2. Measurements and canned responses are always sorted in alpha numeric.

I was playing with trying to make a sticky toolbar/tab container here. That turned out to be a much more committed endeavor given essentially everything but the body content becomes `position: fixed`, and there are quite a few layout bugs with that. 

We can definitely make that happen; I'm still pro-making it work. It's just gonna take a watchful eye and a decent chunk of time. I might need to gather inspiration from other implementations too to see what might help make the CSS easier.

**Comment by DanielCaspers** [comment]
@scaspers , please check out the new behavior. It isn't perfect, and I really should still have that sticky header (#61), but now the new measurements will be _very close_ to the top, if not at the top. The new default response name is "A new response" instead of "New response", so just taking advantage of alpha sort.
