### ISSUE TITLE
Checklist images for the cards don't always load

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#63]
The relative references seem to break on the new server.  The code inspector shows the href as "../../../Uploads/....".

If I inspect the code and change the href to "/stable/Uploads/....."  OR "../../Uploads/...." then it works.
On the old server these options both work too.

**Comment by DanielCaspers** [comment]
Fix is applied to stable. You can see the commit patch review by clicking on the commit reference in this issue. I shouldn't have had relative paths in there in the first place. Not a sensible thing for a client to do when requesting static assets in my opinion. Whoops...

If the fix isn't working for you, try a cache clear. I've disabled mine using "Disable Cache" checkbox in Chrome Dev Tools.

@scaspers, Please close when you verify it works on new server.

**Comment by DanielCaspers** [comment]
So I just took a second look at DI2 server. Perhaps what we want to add are the following [Apache file system alias configurations](https://httpd.apache.org/docs/trunk/urlmapping.html#outside)? 

If that isn't the right approach, is it possible that the _DocumentRoot_ isn't the same for all servers? 

I'm trying to add all possible paths that might give us the equivalent of "WebRoot" since the ApplicationRoot is different in this context I think (hence, why its trying to access one level above). I tried pushing an app that has additional diagnostics to Nightly-A. The about page extra cards with server paths. 

I need I restart so I can continue pushing builds... I bricked the server somehow. IDK what happened.

**Comment by DanielCaspers** [comment]
I attempted to apply a fix this morning to the inspections view specifically in nightly-b, but it for some reason breaks as it doesn't find photos at img src "nightly-b/Uploads/..."

Copy it over to the new server and take a look?

**Comment by scaspers** [comment]
Copied to di2 and it has the same response.  It is not pre-pending the "/nightly-b" to those images. 
ALSO, it is not pre-pending "/nighly-b" to the favicon reference.
I can make those alias entries in apache to cure the problem but this shouldn't be fixed that way as it cannot fix the favicon path.

**Comment by DanielCaspers** [comment]
I think I need to statically add a favicon. I never manually added one so if anything it came for free from the asp.net server or something.

I'll have to undo changes later. I'll call you the next time we can test the aliasing with the old path strategy

**Comment by DanielCaspers** [comment]
The checklist images no longer work due to database changes. Further database changes to images will be required to make this work again.

**Comment by scaspers** [comment]
This is not needed.
