### ISSUE TITLE
Work Order notes

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#73]
This would be notes specific to a work order and not seen by the customer.  Typically edited by techs and consumed by service advisers but also could be edited by the service adviser.  
Data could be owned by DI or D3 as it will be used by both apps and likely edited by both apps.  There will be a desire for the data to live for atleast 2 years.

**Comment by DanielCaspers** [comment]
May have design dependencies on #20 . If that is the case, we will not include in V1.0 launch

**Comment by DanielCaspers** [comment]
The UI and the connective code of this feature is up on DI2.  

@scaspers, @YoMurphy, LMK If you want the CustomerVehicleSummary grouped on one side instead of flexed in between the two items, or if you'd like to tweak the title of the Inspection Item Note dialog or the Work Order Notes dialog. 

![image](https://user-images.githubusercontent.com/6056563/36358533-ba1ebc96-14d5-11e8-8013-6cd4dec26fc4.png)

![image](https://user-images.githubusercontent.com/6056563/36358553-eb3d55ee-14d5-11e8-8575-6c585ee9f707.png)

**Comment by DanielCaspers** [comment]
This feature is now awaiting https://github.com/scaspers/D3-API/issues/16 for completion

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy, note about the current design of the "Work Order Notes" locking scheme.

Right now, when a user clicks "Add" in the work order notes dialog, 
1) Lock is requested at that time.
2) If unlocked, proceeds to set the order notes on the work order to what the user entered.

If they are unable to obtain a lock, their changes are lost. They would see

![image](https://user-images.githubusercontent.com/6056563/38006732-ddc6686c-320b-11e8-8ef5-1e7b81602eef.png)

If you would like me to lock the work order when a user opens the work order notes dialog, we can do that as well. I decided against that originally because users who want to just read the work order notes shouldn't get the lock IMO. 

If this isn't sufficient, we can discuss other options, like a read only vs read-write mode for this dialog, forcing the user to explicitly request the lock before they can make changes.

**Comment by DanielCaspers** [comment]
@scaspers, I snuck in the verbiage fix you were asking for on the work order note dialog.

![image](https://user-images.githubusercontent.com/6056563/38458306-699f36d0-3a62-11e8-8f83-ca02e71cc362.png)

If you want me to change the other multi-line input tags into textarea tags, lets file under a new ticket or under #54 .
