### ISSUE TITLE
Error when clicking on vehicle tab

### ISSUE THREAD

**Issue by scaspers** [DanielCaspers/DigitalInspection#83]
This error occurs when there is no VIN in the work order.  I think it may be because the vehicleNotes is returned NULL rather than an empty array.  Should DI be changed or the D3-API?

![image](https://user-images.githubusercontent.com/12421599/37355441-ccbd7f34-26b1-11e8-9c8c-dc906452450d.png)

**Comment by DanielCaspers** [comment]
@scaspers, could you give me the output of the WorkOrders/Json/004602905 against this api? I can't test anymore since I don't have a user on the production system. 
I'm betting it has to do with either the WorkOrderNotes, WorkDescription, or another list/array type that is null.

Uncertain which side should fix until you show me what its doing.

**Comment by DanielCaspers** [comment]
@scaspers, so I took a look at https://di.murphyauto.net/WorkOrders/JsonForOrder?workOrderId=004602905, and was able to see that the work order is mapped in a sane way. The only thing that looks potentially dangerous to me is that RecommendedServices are null and not an empty list. 

Still uncertain the exact issue until I can follow along in my own debugger locally, since Nulls are notoriously difficult to debug from a log. 

You could try making a dummy RS and see if that changes the behavior it if you don't want to give me a user on the production box.

**Comment by DanielCaspers** [comment]
@scaspers, did you address this from your end? I can't remember what resolution we agreed on.

**Comment by scaspers** [comment]
This was corrected in the D3-API and is live for v1 & v2.  vehicleNotes now returns an empty string array if the VIN is null.
